<?php

namespace ContainerMHEh0ok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMukadiChartJs_NativeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'mukadi_chart_js.native' shared service.
     *
     * @return \Mukadi\ChartJSBundle\Chart\NativeBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mukadi'.\DIRECTORY_SEPARATOR.'chartjs-builder'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'AbstractBuilder.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'mukadi'.\DIRECTORY_SEPARATOR.'chartjs-bundle'.\DIRECTORY_SEPARATOR.'Chart'.\DIRECTORY_SEPARATOR.'NativeBuilder.php';

        return $container->services['mukadi_chart_js.native'] = new \Mukadi\ChartJSBundle\Chart\NativeBuilder(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
