<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO2Cz2TW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO2Cz2TW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO2Cz2TW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO2Cz2TW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO2Cz2TW\App_KernelDevDebugContainer([
    'container.build_hash' => 'O2Cz2TW',
    'container.build_id' => '83a881c5',
    'container.build_time' => 1602060354,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO2Cz2TW');
